<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap,org.apache.sling.api.resource.Resource" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a leagues as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("title", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n## " + v + "\n\n");
  }
  {
    Resource rows = resource.getChild("items");
    if (rows != null && rows.hasChildren()) {
      out.write("\n| " + "Image" + " | " + "Image Alt Text" + " | " + "Title" + " | " + "Text" + " |\n");
      out.write("|---|---|---|---|\n");
      for (Resource row : rows.getChildren()) {
        ValueMap rv = row.getValueMap();
        out.write("| " + rv.get("image", "") + " | " + rv.get("imagealt", "") + " | " + rv.get("title", "") + " | " + rv.get("text", "") + " |\n");
      }
      out.write("\n");
    }
  }
%>
