<%@ page session="false" contentType="text/plain;charset=UTF-8" pageEncoding="UTF-8"
    import="org.apache.sling.api.resource.ValueMap,org.apache.sling.api.resource.Resource" %>
<%@ taglib prefix="sling" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<sling:defineObjects/>
<%
  // Generated by percli hatch (mdgen) from model.json — do not edit by hand.
  // Renders the authored properties of a register as Markdown for LLMs.
  ValueMap vm = resource.getValueMap();
  {
    String v = vm.get("title", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n## " + v + "\n\n");
  }
  {
    String v = vm.get("text", "")
        .replaceAll("(?i)<br\\s*/?>", "\n").replaceAll("(?i)</p>", "\n\n")
        .replaceAll("<[^>]+>", " ").replaceAll("&nbsp;", " ").replaceAll("&amp;", "&")
        .replaceAll("[ \\t]+", " ").replaceAll("\\n{3,}", "\n\n").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    Resource rows = resource.getChild("leagues");
    if (rows != null && rows.hasChildren()) {
      out.write("\n| " + "Option" + " | " + "Value (optional, defaults to the option text)" + " |\n");
      out.write("|---|---|\n");
      for (Resource row : rows.getChildren()) {
        ValueMap rv = row.getValueMap();
        out.write("| " + rv.get("text", "") + " | " + rv.get("value", "") + " |\n");
      }
      out.write("\n");
    }
  }
  {
    Resource rows = resource.getChild("levels");
    if (rows != null && rows.hasChildren()) {
      out.write("\n| " + "Option" + " | " + "Value (optional, defaults to the option text)" + " |\n");
      out.write("|---|---|\n");
      for (Resource row : rows.getChildren()) {
        ValueMap rv = row.getValueMap();
        out.write("| " + rv.get("text", "") + " | " + rv.get("value", "") + " |\n");
      }
      out.write("\n");
    }
  }
  {
    String v = vm.get("namelabel", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("agelabel", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("emaillabel", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("leaguelabel", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("levellabel", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("buttontext", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("sendingtext", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("successtext", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("errortext", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("note", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
  {
    String v = vm.get("action", "").replaceAll("<[^>]+>", " ").replaceAll("[ \\t]+", " ").trim();
    if (!v.isEmpty()) out.write("\n" + v + "\n\n");
  }
%>
